# Generated by Django 4.0.2 on 2022-02-28 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0005_alter_product_picture_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture_link',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
